import type { LeaseRenewal, RecurringCharge, ChargeTransition } from './types';
import { RenewalStatus, MTMPolicy, OwnerApprovalStatus, NewTermOption } from './types';

export const MOCK_TODAY = '2025-03-15';

function daysFromToday(n: number): string {
    const d = new Date('2025-03-15');
    d.setDate(d.getDate() + n);
    return d.toISOString().split('T')[0];
}

function daysAgo(n: number): string {
    const d = new Date('2025-03-15');
    d.setDate(d.getDate() - n);
    return d.toISOString().split('T')[0];
}

const PORTFOLIOS = {
    sunrise: { id: 'p1', name: 'Sunrise Properties' },
    metro: { id: 'p2', name: 'Metro Rentals Group' },
    campus: { id: 'p3', name: 'Campus Housing Co.' },
    legacy: { id: 'p4', name: 'Legacy Real Estate' },
};

let _idCounter = 0;
function nextId(prefix: string) { return `${prefix}${++_idCounter}`; }

interface RenewalInput {
    id: string;
    tenant: { firstName: string; lastName: string; email: string; phone: string; portalAccess?: boolean };
    owner: { firstName: string; lastName: string; email: string; phone: string; requiresApproval: boolean };
    property: { address: string; unitNumber?: string; city: string; state: string; zip: string; type: 'single_family' | 'duplex' | 'condo' | 'apartment' };
    portfolio: keyof typeof PORTFOLIOS;
    currentRent: number;
    proposedRent: number;
    leaseEndDaysFromToday: number;
    proposedTerm: NewTermOption;
    currentTerm?: NewTermOption;
    status: RenewalStatus;
    ownerApproval: OwnerApprovalStatus;
    mtmPolicy: MTMPolicy;
    mtmPremiumPercent?: number;
    charges: RecurringCharge[];
    hasOverlap?: boolean;
}

function buildRenewal(input: RenewalInput): LeaseRenewal {
    const p = PORTFOLIOS[input.portfolio];
    const leaseEndDate = daysFromToday(input.leaseEndDaysFromToday);
    const proposedStartDate = daysFromToday(input.leaseEndDaysFromToday + 1);
    const primaryCharge = input.charges.find(c => c.isRentCharge);
    const netChange = primaryCharge ? input.proposedRent - primaryCharge.amount : input.proposedRent;
    const transition: ChargeTransition = {
        existingCharges: [...input.charges],
        proposedRentAmount: input.proposedRent,
        proposedStartDate,
        hasOverlap: input.hasOverlap ?? false,
        netMonthlyChange: netChange,
        confirmed: false,
    };
    return {
        id: input.id,
        leaseId: `lease-${input.id}`,
        property: {
            id: `prop-${input.id}`,
            address: input.property.address,
            unitNumber: input.property.unitNumber,
            city: input.property.city,
            state: input.property.state,
            zip: input.property.zip,
            portfolioId: p.id,
            portfolioName: p.name,
            propertyType: input.property.type,
        },
        tenant: {
            id: `t-${input.id}`,
            firstName: input.tenant.firstName,
            lastName: input.tenant.lastName,
            email: input.tenant.email,
            phone: input.tenant.phone,
            portalAccessEnabled: input.tenant.portalAccess ?? true,
        },
        owner: {
            id: `o-${input.id}`,
            firstName: input.owner.firstName,
            lastName: input.owner.lastName,
            email: input.owner.email,
            phone: input.owner.phone,
            requiresApproval: input.owner.requiresApproval,
        },
        currentRent: input.currentRent,
        leaseEndDate,
        currentTerm: input.currentTerm ?? NewTermOption.TWELVE_MONTHS,
        proposedRent: input.proposedRent,
        proposedTerm: input.proposedTerm,
        status: input.status,
        ownerApprovalStatus: input.ownerApproval,
        mtmPolicy: input.mtmPolicy,
        mtmPremiumPercent: input.mtmPremiumPercent,
        currentCharges: input.charges,
        chargeTransition: transition,
        offers: [],
        createdAt: daysAgo(90) + 'T00:00:00Z',
        updatedAt: daysAgo(3) + 'T00:00:00Z',
        isDirty: false,
        isSelected: false,
    };
}

function charge(id: string, label: string, amount: number, isRent: boolean, startDaysAgo: number, endDate?: undefined | string): RecurringCharge {
    return { id, label, amount, frequency: 'monthly', startDate: daysAgo(startDaysAgo), endDate, isRentCharge: isRent };
}

// ── GROUP A: STANDARD RENEWALS (16) ────────────────────────
export const MOCK_RENEWALS_A: LeaseRenewal[] = [
    buildRenewal({ id: 'a01', tenant: { firstName: 'Marcus', lastName: 'Thompson', email: 'marcus.thompson@email.com', phone: '(512) 334-8821' }, owner: { firstName: 'David', lastName: 'Park', email: 'david.park@sunriseprop.com', phone: '(512) 300-1001', requiresApproval: true }, property: { address: '2847 Ridgemont Dr', city: 'Austin', state: 'TX', zip: '78745', type: 'single_family' }, portfolio: 'sunrise', currentRent: 1850, proposedRent: 1924, leaseEndDaysFromToday: 12, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a01-1', 'Monthly Rent', 1850, true, 365), charge('c-a01-2', 'Pet Fee', 50, false, 365)] }),
    buildRenewal({ id: 'a02', tenant: { firstName: 'Jennifer', lastName: 'Walsh', email: 'j.walsh@gmail.com', phone: '(720) 445-9012' }, owner: { firstName: 'Sandra', lastName: 'Kim', email: 's.kim@metrorent.com', phone: '(720) 300-1002', requiresApproval: false }, property: { address: '1200 Larimer St', unitNumber: '4B', city: 'Denver', state: 'CO', zip: '80204', type: 'apartment' }, portfolio: 'metro', currentRent: 1425, proposedRent: 1482, leaseEndDaysFromToday: 18, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-a02-1', 'Monthly Rent', 1425, true, 365), charge('c-a02-2', 'Parking', 75, false, 365)] }),
    buildRenewal({ id: 'a03', tenant: { firstName: 'Robert', lastName: 'Castillo', email: 'rcastillo@yahoo.com', phone: '(713) 667-3341' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-1003', requiresApproval: true }, property: { address: '5512 Westheimer Rd', city: 'Houston', state: 'TX', zip: '77056', type: 'duplex' }, portfolio: 'legacy', currentRent: 1650, proposedRent: 1733, leaseEndDaysFromToday: 25, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.PREMIUM, mtmPremiumPercent: 10, charges: [charge('c-a03-1', 'Monthly Rent', 1650, true, 365)] }),
    buildRenewal({ id: 'a04', tenant: { firstName: 'Patricia', lastName: 'Nguyen', email: 'p.nguyen@outlook.com', phone: '(505) 891-2234' }, owner: { firstName: 'James', lastName: 'Wilson', email: 'jwilson@sunriseprop.com', phone: '(505) 300-1004', requiresApproval: false }, property: { address: '3301 Central Ave NW', city: 'Albuquerque', state: 'NM', zip: '87105', type: 'condo' }, portfolio: 'sunrise', currentRent: 1175, proposedRent: 1222, leaseEndDaysFromToday: 31, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OWNER_APPROVED, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a04-1', 'Monthly Rent', 1175, true, 365), charge('c-a04-2', 'Storage Unit', 45, false, 180)] }),
    buildRenewal({ id: 'a05', tenant: { firstName: 'Kevin', lastName: "O'Brien", email: 'kobrien@gmail.com', phone: '(512) 774-5521' }, owner: { firstName: 'Lisa', lastName: 'Chang', email: 'lchang@metrorent.com', phone: '(512) 300-1005', requiresApproval: false }, property: { address: '800 Congress Ave', unitNumber: '12', city: 'Austin', state: 'TX', zip: '78701', type: 'apartment' }, portfolio: 'metro', currentRent: 2100, proposedRent: 2184, leaseEndDaysFromToday: 35, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.SIGNED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-a05-1', 'Monthly Rent', 2100, true, 365), charge('c-a05-2', 'Covered Parking', 100, false, 365), charge('c-a05-3', 'Pet Fee', 65, false, 365)] }),
    buildRenewal({ id: 'a06', tenant: { firstName: 'Amanda', lastName: 'Foster', email: 'afoster@icloud.com', phone: '(303) 554-8823' }, owner: { firstName: 'Robert', lastName: 'Chen', email: 'rchen@legacyre.com', phone: '(303) 300-1006', requiresApproval: true }, property: { address: '1847 Pearl St', city: 'Denver', state: 'CO', zip: '80302', type: 'single_family' }, portfolio: 'legacy', currentRent: 2350, proposedRent: 2420, leaseEndDaysFromToday: 42, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a06-1', 'Monthly Rent', 2350, true, 365)] }),
    buildRenewal({ id: 'a07', tenant: { firstName: 'Derek', lastName: 'Washington', email: 'dwash@email.com', phone: '(713) 330-9944' }, owner: { firstName: 'Nancy', lastName: 'Powell', email: 'npowell@sunriseprop.com', phone: '(713) 300-1007', requiresApproval: false }, property: { address: '6221 Bellaire Blvd', city: 'Houston', state: 'TX', zip: '77081', type: 'single_family' }, portfolio: 'sunrise', currentRent: 1550, proposedRent: 1612, leaseEndDaysFromToday: 48, proposedTerm: NewTermOption.SIX_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.PREMIUM, mtmPremiumPercent: 15, charges: [charge('c-a07-1', 'Monthly Rent', 1550, true, 365)] }),
    buildRenewal({ id: 'a08', tenant: { firstName: 'Rachel', lastName: 'Martinez', email: 'rachel.m@gmail.com', phone: '(505) 442-7761' }, owner: { firstName: 'Tom', lastName: 'Bradley', email: 'tbradley@metrorent.com', phone: '(505) 300-1008', requiresApproval: false }, property: { address: '500 Marquette Ave NW', unitNumber: '3A', city: 'Albuquerque', state: 'NM', zip: '87102', type: 'apartment' }, portfolio: 'metro', currentRent: 995, proposedRent: 1035, leaseEndDaysFromToday: 55, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.COMPLETED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a08-1', 'Monthly Rent', 995, true, 365)] }),
    buildRenewal({ id: 'a09', tenant: { firstName: 'Steven', lastName: 'Park', email: 's.park@outlook.com', phone: '(512) 887-3312' }, owner: { firstName: 'David', lastName: 'Park', email: 'david.park@sunriseprop.com', phone: '(512) 300-1009', requiresApproval: true }, property: { address: '4102 South Lamar Blvd', city: 'Austin', state: 'TX', zip: '78704', type: 'duplex' }, portfolio: 'sunrise', currentRent: 1750, proposedRent: 1820, leaseEndDaysFromToday: 22, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.REQUIRES_ACTION, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-a09-1', 'Monthly Rent', 1750, true, 365), charge('c-a09-2', 'Lawn Care', 80, false, 365)] }),
    buildRenewal({ id: 'a10', tenant: { firstName: 'Michelle', lastName: 'Brooks', email: 'mbrooks@yahoo.com', phone: '(720) 334-6654' }, owner: { firstName: 'Sandra', lastName: 'Kim', email: 's.kim@metrorent.com', phone: '(720) 300-1010', requiresApproval: false }, property: { address: '2400 17th St', unitNumber: '7C', city: 'Denver', state: 'CO', zip: '80202', type: 'apartment' }, portfolio: 'metro', currentRent: 1680, proposedRent: 1747, leaseEndDaysFromToday: 29, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OWNER_APPROVED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-a10-1', 'Monthly Rent', 1680, true, 365), charge('c-a10-2', 'Parking', 90, false, 365)] }),
    buildRenewal({ id: 'a11', tenant: { firstName: 'Brian', lastName: 'Scott', email: 'bscott@gmail.com', phone: '(713) 221-5578' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-1011', requiresApproval: true }, property: { address: '9834 Katy Freeway', city: 'Houston', state: 'TX', zip: '77055', type: 'single_family' }, portfolio: 'legacy', currentRent: 1900, proposedRent: 1976, leaseEndDaysFromToday: 38, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a11-1', 'Monthly Rent', 1900, true, 365)] }),
    buildRenewal({ id: 'a12', tenant: { firstName: 'Carol', lastName: 'Jenkins', email: 'carol.j@icloud.com', phone: '(505) 664-3321' }, owner: { firstName: 'James', lastName: 'Wilson', email: 'jwilson@sunriseprop.com', phone: '(505) 300-1012', requiresApproval: false }, property: { address: '712 Rio Grande Blvd NW', city: 'Albuquerque', state: 'NM', zip: '87104', type: 'condo' }, portfolio: 'sunrise', currentRent: 1250, proposedRent: 1288, leaseEndDaysFromToday: 61, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.SIGNED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a12-1', 'Monthly Rent', 1250, true, 365)] }),
    buildRenewal({ id: 'a13', tenant: { firstName: 'Daniel', lastName: 'Rivera', email: 'd.rivera@email.com', phone: '(512) 990-1123' }, owner: { firstName: 'Lisa', lastName: 'Chang', email: 'lchang@metrorent.com', phone: '(512) 300-1013', requiresApproval: false }, property: { address: '600 Nueces St', unitNumber: '2F', city: 'Austin', state: 'TX', zip: '78701', type: 'apartment' }, portfolio: 'metro', currentRent: 1395, proposedRent: 1451, leaseEndDaysFromToday: 44, proposedTerm: NewTermOption.SIX_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.CONDITIONAL, charges: [charge('c-a13-1', 'Monthly Rent', 1395, true, 365), charge('c-a13-2', 'Pet Fee', 55, false, 180)] }),
    buildRenewal({ id: 'a14', tenant: { firstName: 'Susan', lastName: 'Taylor', email: 'staylor@yahoo.com', phone: '(303) 776-8890' }, owner: { firstName: 'Robert', lastName: 'Chen', email: 'rchen@legacyre.com', phone: '(303) 300-1014', requiresApproval: true }, property: { address: '3344 Speer Blvd', city: 'Denver', state: 'CO', zip: '80211', type: 'duplex' }, portfolio: 'legacy', currentRent: 2200, proposedRent: 2288, leaseEndDaysFromToday: 52, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a14-1', 'Monthly Rent', 2200, true, 365), charge('c-a14-2', 'Garage', 125, false, 365)] }),
    buildRenewal({ id: 'a15', tenant: { firstName: 'Gary', lastName: 'Hernandez', email: 'ghernandez@outlook.com', phone: '(713) 445-2231' }, owner: { firstName: 'Nancy', lastName: 'Powell', email: 'npowell@sunriseprop.com', phone: '(713) 300-1015', requiresApproval: false }, property: { address: '7801 Westpark Dr', city: 'Houston', state: 'TX', zip: '77063', type: 'single_family' }, portfolio: 'sunrise', currentRent: 1475, proposedRent: 1534, leaseEndDaysFromToday: 66, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-a15-1', 'Monthly Rent', 1475, true, 365)] }),
    buildRenewal({ id: 'a16', tenant: { firstName: 'Lisa', lastName: 'Patel', email: 'lpatel@gmail.com', phone: '(505) 332-9087' }, owner: { firstName: 'Tom', lastName: 'Bradley', email: 'tbradley@metrorent.com', phone: '(505) 300-1016', requiresApproval: false }, property: { address: '100 Gold Ave SW', unitNumber: '8B', city: 'Albuquerque', state: 'NM', zip: '87102', type: 'apartment' }, portfolio: 'metro', currentRent: 1125, proposedRent: 1158, leaseEndDaysFromToday: 71, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.COMPLETED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-a16-1', 'Monthly Rent', 1125, true, 365)] }),
];

// ── GROUP B: OVERLAP RISK RECORDS (6) ──────────────────────
export const MOCK_RENEWALS_B: LeaseRenewal[] = [
    buildRenewal({ id: 'b01', tenant: { firstName: 'Thomas', lastName: 'Mitchell', email: 'tmitchell@email.com', phone: '(512) 553-7741' }, owner: { firstName: 'David', lastName: 'Park', email: 'david.park@sunriseprop.com', phone: '(512) 300-2001', requiresApproval: true }, property: { address: '1923 Barton Springs Rd', city: 'Austin', state: 'TX', zip: '78704', type: 'single_family' }, portfolio: 'sunrise', currentRent: 2050, proposedRent: 2132, leaseEndDaysFromToday: 14, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.ALLOWED, hasOverlap: true, charges: [charge('c-b01-1', 'Monthly Rent', 2050, true, 730), charge('c-b01-2', 'Pet Fee', 75, false, 730)] }),
    buildRenewal({ id: 'b02', tenant: { firstName: 'Angela', lastName: 'Moore', email: 'angela.moore@yahoo.com', phone: '(303) 667-4412' }, owner: { firstName: 'Sandra', lastName: 'Kim', email: 's.kim@metrorent.com', phone: '(303) 300-2002', requiresApproval: false }, property: { address: '1550 Market St', unitNumber: '5D', city: 'Denver', state: 'CO', zip: '80202', type: 'apartment' }, portfolio: 'metro', currentRent: 1580, proposedRent: 1643, leaseEndDaysFromToday: 9, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, hasOverlap: true, charges: [charge('c-b02-1', 'Monthly Rent', 1580, true, 365), charge('c-b02-2', 'Parking', 80, false, 365)] }),
    buildRenewal({ id: 'b03', tenant: { firstName: 'Raymond', lastName: 'Garcia', email: 'rgarcia@outlook.com', phone: '(713) 884-5530' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-2003', requiresApproval: true }, property: { address: '3300 Buffalo Speedway', city: 'Houston', state: 'TX', zip: '77098', type: 'duplex' }, portfolio: 'legacy', currentRent: 1780, proposedRent: 1851, leaseEndDaysFromToday: 19, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.REQUIRES_ACTION, mtmPolicy: MTMPolicy.PREMIUM, mtmPremiumPercent: 10, hasOverlap: true, charges: [charge('c-b03-1', 'Monthly Rent', 1780, true, 365)] }),
    buildRenewal({ id: 'b04', tenant: { firstName: 'Donna', lastName: 'White', email: 'donna.white@gmail.com', phone: '(505) 773-2298' }, owner: { firstName: 'James', lastName: 'Wilson', email: 'jwilson@sunriseprop.com', phone: '(505) 300-2004', requiresApproval: false }, property: { address: '2211 Mountain Rd NW', city: 'Albuquerque', state: 'NM', zip: '87104', type: 'condo' }, portfolio: 'sunrise', currentRent: 1320, proposedRent: 1373, leaseEndDaysFromToday: 26, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.ALLOWED, hasOverlap: true, charges: [charge('c-b04-1', 'Monthly Rent', 1320, true, 365), charge('c-b04-2', 'Storage', 40, false, 180)] }),
    buildRenewal({ id: 'b05', tenant: { firstName: 'Frank', lastName: 'Robinson', email: 'frank.r@icloud.com', phone: '(512) 221-8874' }, owner: { firstName: 'Lisa', lastName: 'Chang', email: 'lchang@metrorent.com', phone: '(512) 300-2005', requiresApproval: false }, property: { address: '400 West 2nd St', unitNumber: '9A', city: 'Austin', state: 'TX', zip: '78701', type: 'apartment' }, portfolio: 'metro', currentRent: 1890, proposedRent: 1965, leaseEndDaysFromToday: 11, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, hasOverlap: true, charges: [charge('c-b05-1', 'Monthly Rent', 1890, true, 365), charge('c-b05-2', 'Covered Parking', 110, false, 365), charge('c-b05-3', 'Pet Fee', 60, false, 365)] }),
    buildRenewal({ id: 'b06', tenant: { firstName: 'Nancy', lastName: 'Adams', email: 'nadams@yahoo.com', phone: '(303) 445-6612' }, owner: { firstName: 'Robert', lastName: 'Chen', email: 'rchen@legacyre.com', phone: '(303) 300-2006', requiresApproval: true }, property: { address: '4417 Tennyson St', city: 'Denver', state: 'CO', zip: '80212', type: 'single_family' }, portfolio: 'legacy', currentRent: 2280, proposedRent: 2371, leaseEndDaysFromToday: 17, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.ALLOWED, hasOverlap: true, charges: [charge('c-b06-1', 'Monthly Rent', 2280, true, 730), charge('c-b06-2', 'Lawn Care', 95, false, 365)] }),
];

// ── GROUP C: CAMPUS / SEASONAL RECORDS (8) ─────────────────
const campusOwner = { firstName: 'University Housing', lastName: 'LLC', email: 'uhousing@campus.com', phone: '(512) 300-3000', requiresApproval: false };
export const MOCK_RENEWALS_C: LeaseRenewal[] = [
    buildRenewal({ id: 'c01', tenant: { firstName: 'Alex', lastName: 'Chen', email: 'alex.chen@university.edu', phone: '(512) 334-2211' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '101', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 875, proposedRent: 920, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c01-1', 'Monthly Rent', 875, true, 240)] }),
    buildRenewal({ id: 'c02', tenant: { firstName: 'Megan', lastName: 'Sullivan', email: 'meg.sullivan@university.edu', phone: '(512) 887-4432' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '102', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 875, proposedRent: 920, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c02-1', 'Monthly Rent', 875, true, 240)] }),
    buildRenewal({ id: 'c03', tenant: { firstName: 'Tyler', lastName: 'Brooks', email: 't.brooks@university.edu', phone: '(512) 663-9901' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '103', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 895, proposedRent: 941, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c03-1', 'Monthly Rent', 895, true, 240)] }),
    buildRenewal({ id: 'c04', tenant: { firstName: 'Samantha', lastName: 'Lee', email: 'sam.lee@university.edu', phone: '(512) 774-3345' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '201', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 925, proposedRent: 972, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c04-1', 'Monthly Rent', 925, true, 240)] }),
    buildRenewal({ id: 'c05', tenant: { firstName: 'Jordan', lastName: 'Rivera', email: 'j.rivera@university.edu', phone: '(512) 990-5566' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '202', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 925, proposedRent: 963, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c05-1', 'Monthly Rent', 925, true, 240)] }),
    buildRenewal({ id: 'c06', tenant: { firstName: 'Chloe', lastName: 'Park', email: 'chloe.p@university.edu', phone: '(512) 553-1122' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '203', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 950, proposedRent: 988, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c06-1', 'Monthly Rent', 950, true, 240)] }),
    buildRenewal({ id: 'c07', tenant: { firstName: 'Brandon', lastName: 'White', email: 'b.white@university.edu', phone: '(512) 221-7744' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '204', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 950, proposedRent: 998, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c07-1', 'Monthly Rent', 950, true, 240)] }),
    buildRenewal({ id: 'c08', tenant: { firstName: 'Emma', lastName: 'Johnson', email: 'emma.j@university.edu', phone: '(512) 445-8821' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '205', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 975, proposedRent: 1024, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-c08-1', 'Monthly Rent', 975, true, 240)] }),
];

// ── GROUP D: MTM EDGE CASES (8) ───────────────────────────
export const MOCK_RENEWALS_D: LeaseRenewal[] = [
    buildRenewal({ id: 'd01', tenant: { firstName: 'Gloria', lastName: 'Turner', email: 'gloria.t@gmail.com', phone: '(720) 334-9981' }, owner: { firstName: 'Sandra', lastName: 'Kim', email: 's.kim@metrorent.com', phone: '(720) 300-4001', requiresApproval: false }, property: { address: '900 Grant St', unitNumber: '2A', city: 'Denver', state: 'CO', zip: '80203', type: 'apartment' }, portfolio: 'metro', currentRent: 1460, proposedRent: 1460, leaseEndDaysFromToday: 28, proposedTerm: NewTermOption.MONTH_TO_MONTH, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-d01-1', 'Monthly Rent', 1460, true, 365)] }),
    buildRenewal({ id: 'd02', tenant: { firstName: 'Harold', lastName: 'Lewis', email: 'harold.l@yahoo.com', phone: '(512) 881-3312' }, owner: { firstName: 'David', lastName: 'Park', email: 'david.park@sunriseprop.com', phone: '(512) 300-4002', requiresApproval: true }, property: { address: '5023 Duval St', city: 'Austin', state: 'TX', zip: '78751', type: 'single_family' }, portfolio: 'sunrise', currentRent: 1700, proposedRent: 1870, leaseEndDaysFromToday: 33, proposedTerm: NewTermOption.MONTH_TO_MONTH, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.REQUIRES_ACTION, mtmPolicy: MTMPolicy.PREMIUM, mtmPremiumPercent: 10, charges: [charge('c-d02-1', 'Monthly Rent', 1700, true, 365)] }),
    buildRenewal({ id: 'd03', tenant: { firstName: 'Irene', lastName: 'Cox', email: 'irene.cox@icloud.com', phone: '(505) 667-4453' }, owner: { firstName: 'James', lastName: 'Wilson', email: 'jwilson@sunriseprop.com', phone: '(505) 300-4003', requiresApproval: false }, property: { address: '700 Lomas Blvd NE', unitNumber: '4C', city: 'Albuquerque', state: 'NM', zip: '87102', type: 'apartment' }, portfolio: 'sunrise', currentRent: 1050, proposedRent: 1050, leaseEndDaysFromToday: 21, proposedTerm: NewTermOption.MONTH_TO_MONTH, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-d03-1', 'Monthly Rent', 1050, true, 365)] }),
    buildRenewal({ id: 'd04', tenant: { firstName: 'James', lastName: 'Murray', email: 'j.murray@outlook.com', phone: '(713) 553-7761' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-4004', requiresApproval: false }, property: { address: '4441 Montrose Blvd', city: 'Houston', state: 'TX', zip: '77006', type: 'condo' }, portfolio: 'legacy', currentRent: 1920, proposedRent: 1920, leaseEndDaysFromToday: 16, proposedTerm: NewTermOption.MONTH_TO_MONTH, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.CONDITIONAL, charges: [charge('c-d04-1', 'Monthly Rent', 1920, true, 365)] }),
    buildRenewal({ id: 'd05', tenant: { firstName: 'Karen', lastName: 'Bell', email: 'k.bell@email.com', phone: '(303) 221-4455' }, owner: { firstName: 'Robert', lastName: 'Chen', email: 'rchen@legacyre.com', phone: '(303) 300-4005', requiresApproval: true }, property: { address: '1801 Wewatta St', city: 'Denver', state: 'CO', zip: '80202', type: 'apartment' }, portfolio: 'legacy', currentRent: 1540, proposedRent: 1602, leaseEndDaysFromToday: 39, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.PREMIUM, mtmPremiumPercent: 12, charges: [charge('c-d05-1', 'Monthly Rent', 1540, true, 365)] }),
    buildRenewal({ id: 'd06', tenant: { firstName: 'Larry', lastName: 'Young', email: 'lyoung@gmail.com', phone: '(512) 445-6677' }, owner: { firstName: 'Lisa', lastName: 'Chang', email: 'lchang@metrorent.com', phone: '(512) 300-4006', requiresApproval: false }, property: { address: '1100 S Congress Ave', city: 'Austin', state: 'TX', zip: '78704', type: 'condo' }, portfolio: 'metro', currentRent: 1380, proposedRent: 1421, leaseEndDaysFromToday: 57, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.SIGNED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-d06-1', 'Monthly Rent', 1380, true, 365)] }),
    buildRenewal({ id: 'd07', tenant: { firstName: 'Monica', lastName: 'Reed', email: 'mreed@yahoo.com', phone: '(713) 998-3344' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-4007', requiresApproval: true }, property: { address: '2727 Kirby Dr', city: 'Houston', state: 'TX', zip: '77098', type: 'duplex' }, portfolio: 'legacy', currentRent: 1820, proposedRent: 1893, leaseEndDaysFromToday: 34, proposedTerm: NewTermOption.SIX_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.CONDITIONAL, charges: [charge('c-d07-1', 'Monthly Rent', 1820, true, 365)] }),
    buildRenewal({ id: 'd08', tenant: { firstName: 'Nathan', lastName: 'Price', email: 'nprice@outlook.com', phone: '(505) 776-9988' }, owner: { firstName: 'James', lastName: 'Wilson', email: 'jwilson@sunriseprop.com', phone: '(505) 300-4008', requiresApproval: false }, property: { address: '400 Lomas Blvd NW', city: 'Albuquerque', state: 'NM', zip: '87102', type: 'condo' }, portfolio: 'sunrise', currentRent: 1150, proposedRent: 1196, leaseEndDaysFromToday: 46, proposedTerm: NewTermOption.TWENTY_FOUR_MONTHS, status: RenewalStatus.OWNER_APPROVED, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-d08-1', 'Monthly Rent', 1150, true, 365)] }),
];

// ── GROUP E: EDGE CASES (8) ───────────────────────────────
export const MOCK_RENEWALS_E: LeaseRenewal[] = [
    buildRenewal({ id: 'e01', tenant: { firstName: 'Bartholomew', lastName: "Krishnamurthy-O'Sullivan", email: 'b.krishnamurthy.osullivan@longdomainname-corp.com', phone: '(303) 112-3344' }, owner: { firstName: 'Robert', lastName: 'Chen', email: 'rchen@legacyre.com', phone: '(303) 300-5001', requiresApproval: true }, property: { address: '123 Main St', city: 'Denver', state: 'CO', zip: '80201', type: 'single_family' }, portfolio: 'legacy', currentRent: 1600, proposedRent: 1664, leaseEndDaysFromToday: 45, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.PENDING, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-e01-1', 'Monthly Rent', 1600, true, 365)] }),
    buildRenewal({ id: 'e02', tenant: { firstName: 'James', lastName: 'Short', email: 'j.short@email.com', phone: '(713) 554-2211' }, owner: { firstName: 'Tom', lastName: 'Bradley', email: 'tbradley@metrorent.com', phone: '(713) 300-5002', requiresApproval: false }, property: { address: '14200 Southwest Freeway Service Rd', unitNumber: '12B (Building C)', city: 'Houston', state: 'TX', zip: '77478', type: 'apartment' }, portfolio: 'metro', currentRent: 1150, proposedRent: 1196, leaseEndDaysFromToday: 33, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-e02-1', 'Monthly Rent', 1150, true, 365)] }),
    buildRenewal({ id: 'e03', tenant: { firstName: 'Alice', lastName: 'Chen', email: 'alice.chen@email.com', phone: '(512) 889-4411' }, owner: { firstName: 'David', lastName: 'Park', email: 'david.park@sunriseprop.com', phone: '(512) 300-5003', requiresApproval: true }, property: { address: '901 First St', city: 'Austin', state: 'TX', zip: '78703', type: 'condo' }, portfolio: 'sunrise', currentRent: 1875, proposedRent: 1950, leaseEndDaysFromToday: 3, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.REQUIRES_ACTION, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-e03-1', 'Monthly Rent', 1875, true, 365)] }),
    buildRenewal({ id: 'e04', tenant: { firstName: 'Bob', lastName: 'Dunn', email: 'bob.dunn@email.com', phone: '(303) 667-8899' }, owner: { firstName: 'Sandra', lastName: 'Kim', email: 's.kim@metrorent.com', phone: '(303) 300-5004', requiresApproval: false }, property: { address: '300 4th St', unitNumber: '6A', city: 'Denver', state: 'CO', zip: '80204', type: 'apartment' }, portfolio: 'metro', currentRent: 1350, proposedRent: 1350, leaseEndDaysFromToday: -5, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-e04-1', 'Monthly Rent', 1350, true, 365)] }),
    buildRenewal({ id: 'e05', tenant: { firstName: 'Carol', lastName: 'Smith', email: 'carol.smith@email.com', phone: '(713) 332-4455' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-5005', requiresApproval: true }, property: { address: '1100 W Gray St', city: 'Houston', state: 'TX', zip: '77019', type: 'duplex' }, portfolio: 'legacy', currentRent: 2100, proposedRent: 1995, leaseEndDaysFromToday: 55, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.TENANT_RESPONDED, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-e05-1', 'Monthly Rent', 2100, true, 365)] }),
    buildRenewal({ id: 'e06', tenant: { firstName: 'David', lastName: 'Brown', email: 'd.brown@email.com', phone: '(210) 554-7788' }, owner: { firstName: 'Nancy', lastName: 'Powell', email: 'npowell@sunriseprop.com', phone: '(210) 300-5006', requiresApproval: false }, property: { address: '4400 N Loop 1604', city: 'San Antonio', state: 'TX', zip: '78249', type: 'single_family' }, portfolio: 'sunrise', currentRent: 2400, proposedRent: 2496, leaseEndDaysFromToday: 40, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.OFFER_SENT, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, hasOverlap: true, charges: [charge('c-e06-1', 'Monthly Rent', 2400, true, 365), charge('c-e06-2', 'Pet Fee (Dog)', 75, false, 365), charge('c-e06-3', 'Pet Fee (Cat)', 50, false, 365), charge('c-e06-4', 'Covered Parking', 125, false, 365), charge('c-e06-5', 'Pool Access', 45, false, 365)] }),
    buildRenewal({ id: 'e07', tenant: { firstName: 'Eve', lastName: 'Davis', email: 'eve.davis@email.com', phone: '(713) 775-3322' }, owner: { firstName: 'Michael', lastName: 'Torres', email: 'm.torres@legacyre.com', phone: '(713) 300-5007', requiresApproval: true }, property: { address: '6612 Richmond Ave', city: 'Houston', state: 'TX', zip: '77057', type: 'condo' }, portfolio: 'legacy', currentRent: 1750, proposedRent: 1820, leaseEndDaysFromToday: 15, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.PENDING, ownerApproval: OwnerApprovalStatus.REQUIRES_ACTION, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-e07-1', 'Monthly Rent', 1750, true, 365)] }),
    buildRenewal({ id: 'e08', tenant: { firstName: 'Frank', lastName: 'Wu', email: 'frank.wu@email.com', phone: '(512) 998-1122' }, owner: campusOwner, property: { address: '2200 Speedway', unitNumber: '301', city: 'Austin', state: 'TX', zip: '78705', type: 'apartment' }, portfolio: 'campus', currentRent: 1050, proposedRent: 1050, leaseEndDaysFromToday: 138, proposedTerm: NewTermOption.TWENTY_FOUR_MONTHS, status: RenewalStatus.SIGNED, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-e08-1', 'Monthly Rent', 1050, true, 240)] }),
];

// ── GROUP F: VACATING RECORDS (6) ─────────────────────────
export const MOCK_RENEWALS_F: LeaseRenewal[] = [
    buildRenewal({ id: 'f01', tenant: { firstName: 'Victor', lastName: 'Morales', email: 'vmorales@email.com', phone: '(505) 443-5511' }, owner: { firstName: 'James', lastName: 'Wilson', email: 'jwilson@sunriseprop.com', phone: '(505) 300-6001', requiresApproval: false }, property: { address: '204 E Palace Ave', city: 'Santa Fe', state: 'NM', zip: '87501', type: 'single_family' }, portfolio: 'sunrise', currentRent: 1650, proposedRent: 1650, leaseEndDaysFromToday: 10, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-f01-1', 'Monthly Rent', 1650, true, 365)] }),
    buildRenewal({ id: 'f02', tenant: { firstName: 'Sandra', lastName: 'Collins', email: 'scollins@gmail.com', phone: '(719) 332-8874' }, owner: { firstName: 'Nancy', lastName: 'Powell', email: 'npowell@sunriseprop.com', phone: '(719) 300-6002', requiresApproval: false }, property: { address: '2155 Cheyenne Blvd', city: 'Colorado Springs', state: 'CO', zip: '80906', type: 'duplex' }, portfolio: 'sunrise', currentRent: 1400, proposedRent: 1400, leaseEndDaysFromToday: 18, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-f02-1', 'Monthly Rent', 1400, true, 365)] }),
    buildRenewal({ id: 'f03', tenant: { firstName: 'Tony', lastName: 'Perez', email: 'tperez@yahoo.com', phone: '(210) 887-2231' }, owner: { firstName: 'Tom', lastName: 'Bradley', email: 'tbradley@metrorent.com', phone: '(210) 300-6003', requiresApproval: false }, property: { address: '5900 NW Loop 410', city: 'San Antonio', state: 'TX', zip: '78238', type: 'apartment' }, portfolio: 'metro', currentRent: 1275, proposedRent: 1275, leaseEndDaysFromToday: 25, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.PREMIUM, mtmPremiumPercent: 10, charges: [charge('c-f03-1', 'Monthly Rent', 1275, true, 365)] }),
    buildRenewal({ id: 'f04', tenant: { firstName: 'Rebecca', lastName: 'Grant', email: 'rgrant@icloud.com', phone: '(505) 665-7742' }, owner: { firstName: 'Robert', lastName: 'Chen', email: 'rchen@legacyre.com', phone: '(505) 300-6004', requiresApproval: true }, property: { address: '415 Don Gaspar Ave', city: 'Santa Fe', state: 'NM', zip: '87501', type: 'condo' }, portfolio: 'legacy', currentRent: 1525, proposedRent: 1525, leaseEndDaysFromToday: 32, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.APPROVED, mtmPolicy: MTMPolicy.CONDITIONAL, charges: [charge('c-f04-1', 'Monthly Rent', 1525, true, 365)] }),
    buildRenewal({ id: 'f05', tenant: { firstName: 'Wayne', lastName: 'Harris', email: 'wharris@email.com', phone: '(719) 221-9908' }, owner: { firstName: 'David', lastName: 'Park', email: 'david.park@sunriseprop.com', phone: '(719) 300-6005', requiresApproval: true }, property: { address: '3650 N Academy Blvd', city: 'Colorado Springs', state: 'CO', zip: '80917', type: 'single_family' }, portfolio: 'sunrise', currentRent: 1800, proposedRent: 1800, leaseEndDaysFromToday: 45, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.ALLOWED, charges: [charge('c-f05-1', 'Monthly Rent', 1800, true, 365)] }),
    buildRenewal({ id: 'f06', tenant: { firstName: 'Diana', lastName: 'Long', email: 'dlong@outlook.com', phone: '(210) 443-6612' }, owner: { firstName: 'Lisa', lastName: 'Chang', email: 'lchang@metrorent.com', phone: '(210) 300-6006', requiresApproval: false }, property: { address: '7959 Fredericksburg Rd', city: 'San Antonio', state: 'TX', zip: '78229', type: 'apartment' }, portfolio: 'metro', currentRent: 1100, proposedRent: 1100, leaseEndDaysFromToday: 14, proposedTerm: NewTermOption.TWELVE_MONTHS, status: RenewalStatus.VACATING, ownerApproval: OwnerApprovalStatus.NOT_REQUIRED, mtmPolicy: MTMPolicy.FORBIDDEN, charges: [charge('c-f06-1', 'Monthly Rent', 1100, true, 365)] }),
];

// ── FULL COMBINED DATASET ─────────────────────────────────
export const MOCK_RENEWALS: LeaseRenewal[] = [
    ...MOCK_RENEWALS_A,
    ...MOCK_RENEWALS_B,
    ...MOCK_RENEWALS_C,
    ...MOCK_RENEWALS_D,
    ...MOCK_RENEWALS_E,
    ...MOCK_RENEWALS_F,
];
